#pragma once

// GENERATED by tools/standalone/codemod_globals.py --gen-shared from .notes/aliases.json (slice A2/A4): globals that several .cpp files declare at one
// original address. Detached mode: the one definition; address mode: nothing (the alias sites keep their `StaticRef`). Do not edit by hand.

namespace notsa::shared {
NOTSA_GLOBAL_SYNTH(NoNode, 0x8A5F44, (CNodeAddress), { std::bit_cast<CNodeAddress>(0xFFFFU) });
NOTSA_GLOBAL_SYNTH(CurDistForCam, 0x8CCB84, (float), { 1.0f });
NOTSA_GLOBAL_SYNTH(BoundingBoxMargin, 0x8D22B0, (float), { 0.35f });
NOTSA_GLOBAL_SYNTH(NextDesiredMoveState, 0x8D237C, (eMoveState), { std::bit_cast<eMoveState>(0x6U) });
NOTSA_GLOBAL_SYNTH(CamColLastRadius, 0xB6EC6C, (float), {});
NOTSA_GLOBAL_SYNTH(CustomBuildingMagic1, 0xC02C14, (uint32), {});
NOTSA_GLOBAL_SYNTH(CustomBuildingMagic2, 0xC02C18, (uint32), {});
NOTSA_GLOBAL_SYNTH(EntityPosChangeThreshold, 0xC18CF0, (float), { 1.0f });
NOTSA_GLOBAL_SYNTH(ScriptRoute, 0xC18D50, (CPointRoute), {});
NOTSA_GLOBAL_SYNTH(ScriptPatrolRoute, 0xC18DB8, (CPatrolRoute), {});
} // namespace notsa::shared
