#pragma once

#include "eModelID.h"

using ModelIndex = notsa::WEnumU16<eModelID>;

namespace ModelIndices {
    NOTSA_GLOBAL_EXTERN(MI_TRAFFICLIGHTS, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_TRAFFICLIGHTS_VERTICAL, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_TRAFFICLIGHTS_MIAMI, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_TRAFFICLIGHTS_VEGAS, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_TRAFFICLIGHTS_TWOVERTICAL, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_TRAFFICLIGHTS_3, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_TRAFFICLIGHTS_4, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_TRAFFICLIGHTS_5, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_TRAFFICLIGHTS_GAY, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_SINGLESTREETLIGHTS1, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_SINGLESTREETLIGHTS2, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_SINGLESTREETLIGHTS3, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_DOUBLESTREETLIGHTS, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_STREETLAMP1, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_STREETLAMP2, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MODELID_CRANE_1, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MODELID_CRANE_2, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MODELID_CRANE_3, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MODELID_CRANE_4, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MODELID_CRANE_5, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MODELID_CRANE_6, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_PARKINGMETER, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_PARKINGMETER2, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_MALLFAN, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_HOTELFAN_NIGHT, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_HOTELFAN_DAY, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_HOTROOMFAN, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_PHONEBOOTH1, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_WASTEBIN, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_BIN, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_POSTBOX1, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_NEWSSTAND, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_TRAFFICCONE, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_DUMP1, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_ROADWORKBARRIER1, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_ROADBLOCKFUCKEDCAR1, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_ROADBLOCKFUCKEDCAR2, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_BUSSIGN1, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_NOPARKINGSIGN1, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_PHONESIGN, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_FIRE_HYDRANT, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_COLLECTABLE1, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_MONEY, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_CARMINE, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_NAUTICALMINE, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_TELLY, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_BRIEFCASE, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_GLASS1, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_GLASS8, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_EXPLODINGBARREL, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_PICKUP_ADRENALINE, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_PICKUP_BODYARMOUR, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_PICKUP_INFO, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_PICKUP_HEALTH, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_PICKUP_BONUS, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_PICKUP_BRIBE, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_PICKUP_KILLFRENZY, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_PICKUP_CAMERA, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_PICKUP_PARACHUTE, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_PICKUP_REVENUE, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_PICKUP_SAVEGAME, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_PICKUP_PROPERTY, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_PICKUP_PROPERTY_FORSALE, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_PICKUP_CLOTHES, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_PICKUP_2P_KILLFRENZY, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_PICKUP_2P_COOP, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_BOLLARDLIGHT, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_FENCE, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_FENCE2, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_BUOY, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_PARKTABLE, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_LAMPPOST1, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_MLAMPPOST, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_BARRIER1, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_LITTLEHA_POLICE, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_TELPOLE02, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_TRAFFICLIGHT01, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_PARKBENCH, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_LIGHTBEAM, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_AIRPORTRADAR, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_RCBOMB, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_BEACHBALL, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_SANDCASTLE1, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_SANDCASTLE2, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_JELLYFISH, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_JELLYFISH01, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_FISH1SINGLE, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_FISH1S, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_FISH2SINGLE, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_FISH2S, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_FISH3SINGLE, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_FISH3S, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_TURTLE, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_DOLPHIN, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_SHARK, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_SUBMARINE, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_ESCALATORSTEP, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_ESCALATORSTEP8, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_LOUNGE_WOOD_UP, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_LOUNGE_TOWEL_UP, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_LOUNGE_WOOD_DN, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_LOTION, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_BEACHTOWEL01, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_BEACHTOWEL02, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_BEACHTOWEL03, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_BEACHTOWEL04, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_BLIMP_NIGHT, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_BLIMP_DAY, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_YT_MAIN_BODY, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_YT_MAIN_BODY2, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_SAMSITE, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_SAMSITE2, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_TRAINCROSSING, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_TRAINCROSSING1, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_MAGNOCRANE, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_CRANETROLLEY, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_QUARRYCRANE_ARM, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_OBJECTFORMAGNOCRANE1, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_OBJECTFORMAGNOCRANE2, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_OBJECTFORMAGNOCRANE3, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_OBJECTFORMAGNOCRANE4, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_OBJECTFORMAGNOCRANE5, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_OBJECTFORBUILDINGSITECRANE1, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_MAGNOCRANE_HOOK, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_HARVESTERBODYPART1, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_HARVESTERBODYPART2, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_HARVESTERBODYPART3, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_HARVESTERBODYPART4, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_GRASSHOUSE, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_GRASSPLANT, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_CRANE_HARNESS, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_CRANE_MAGNET, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_QUARY_ROCK1, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_QUARY_ROCK2, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_QUARY_ROCK3, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_ATM, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_DEAD_TIED_COP, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_WINDSOCK, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_WRECKING_BALL, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_FREEFALL_BOMB, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_WONG_DISH, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_GANG_DRINK, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_GANG_SMOKE, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_RHYMESBOOK, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_KMB_ROCK, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_KMB_PLANK, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_KMB_BOMB, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_MINI_MAGNET, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_HANGING_CARCASS, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_IMY_SHASH_WALL, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_PARACHUTE_BACKPACK, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_OYSTER, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_HORSESHOE, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_OFFROAD_WHEEL, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_FLARE, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_NITRO_BOTTLE_SMALL, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_NITRO_BOTTLE_LARGE, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_NITRO_BOTTLE_DOUBLE, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_HYDRAULICS, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_STEREO_UPGRADE, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_BASKETBALL, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_POOL_CUE_BALL, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_PUNCHBAG, (ModelIndex));
    NOTSA_GLOBAL_EXTERN(MI_IMY_GRAY_CRATE, (ModelIndex));

    inline bool IsRhino(int32 modelId) { return modelId == MODEL_RHINO; }
    inline bool IsVortex(int32 modelId) { return modelId == MODEL_VORTEX; }
    inline bool IsDumper(int32 modelId) { return modelId == MODEL_DUMPER; }
    inline bool IsPacker(int32 modelId) { return modelId == MODEL_PACKER; }
    inline bool IsDozer(int32 modelId) { return modelId == MODEL_DOZER; }
    inline bool IsKart(int32 modelId) { return modelId == MODEL_KART; }
    inline bool IsForklift(int32 modelId) { return modelId == MODEL_FORKLIFT; }
    inline bool IsAndromada(int32 modelId) { return modelId == MODEL_ANDROM; }
    inline bool IsFireTruckLadder(int32 modelId) { return modelId == MODEL_FIRELA; }
    inline bool IsFireTruck(int32 modelId) { return modelId == MODEL_FIRETRUK; }
    inline bool IsCementTruck(int32 modelId) { return modelId == MODEL_CEMENT; }
    inline bool IsCombineHarvester(int32 modelId) { return modelId == MODEL_COMBINE; }

    inline bool IsRCBaron(int32 modelId) { return modelId == MODEL_RCBARON; }
    inline bool IsRCBandit(int32 modelId) { return modelId == MODEL_RCBANDIT; }
    inline bool IsRCTiger(int32 modelId) { return modelId == MODEL_RCTIGER; }
    inline bool IsSandKing(int32 modelId) { return modelId == MODEL_SANDKING; }
    inline bool IsBFInjection(int32 modelId) { return modelId == MODEL_BFINJECT; }
    inline bool IsSwatVan(int32 modelId) { return modelId == MODEL_SWATVAN; }
    inline bool IsNevada(int32 modelId) { return modelId == MODEL_NEVADA; }

    inline bool IsSkimmer(int32 modelId) { return modelId == MODEL_SKIMMER; }

    inline bool IsAmphibiousHeli(int32 modelId) { return modelId == MODEL_SEASPAR || modelId == MODEL_LEVIATHN; }
    inline bool HasWaterCannon(int32 modelId) { return modelId == MODEL_FIRETRUK || modelId == MODEL_SWATVAN; }
    inline bool HasMiscComponent(int32 modelId) {
        return modelId == MODEL_PACKER
            || modelId == MODEL_DOZER
            || modelId == MODEL_DUMPER
            || modelId == MODEL_CEMENT
            || modelId == MODEL_ANDROM
            || modelId == MODEL_FORKLIFT;
    }
    inline bool IsFence1Or2(int32 mi) { return mi == MI_FENCE || mi == MI_FENCE2; }
    void InjectHooks();
}

void InitModelIndices();

void MatchAllModelStrings();

void MatchModelStringUint16(char* name, ModelIndex);

void TestModelIndices();
