// GENERATED by tools/standalone/gen_fakerw_api.py from source/game_sa/RenderWare/rw/*.h -- do not edit by hand.
// Declarations of the RW C functions the game calls (exact RW 3.6 signatures); bodies: source/standalone/rw/*.cpp (P2B-01 ... 09).
#pragma once

// ---- rpanisot.h ----
RwBool RpAnisotPluginAttach(void);

// ---- rphanim.h ----
RpHAnimHierarchy * RpHAnimFrameGetHierarchy(RwFrame *frame);
RwBool RpHAnimFrameSetHierarchy(RwFrame *frame, RpHAnimHierarchy *hierarchy);
RpHAnimHierarchy * RpHAnimHierarchyCreateFromHierarchy(RpHAnimHierarchy *hierarchy, RpHAnimHierarchyFlag flags, RwInt32 maxInterpKeyFrameSize);
RwMatrix * RpHAnimHierarchyGetMatrixArray(RpHAnimHierarchy *hierarchy);
RwMatrix * RpHAnimHierarchyGetNodeMatrix(RpHAnimHierarchy *hierarchy, RwInt32 nodeID);
RwBool RpHAnimHierarchyUpdateMatrices(RpHAnimHierarchy *hierarchy);
RwInt32 RpHAnimIDGetIndex(RpHAnimHierarchy *hierarchy, RwInt32 ID);
void RpHAnimKeyFrameAdd(void *voidOut, void *voidIn1, void *voidIn2);
void RpHAnimKeyFrameBlend(void *voidOut, void *voidIn1, void *voidIn2, RwReal alpha);
void RpHAnimKeyFrameMulRecip(void *voidFrame, void *voidStart);
RwInt32 RpHAnimKeyFrameStreamGetSize(const RtAnimAnimation *animation);
RtAnimAnimation * RpHAnimKeyFrameStreamRead(RwStream *stream, RtAnimAnimation *animation);
RwBool RpHAnimKeyFrameStreamWrite(const RtAnimAnimation *animation, RwStream *stream);
RwBool RpHAnimPluginAttach(void);

// ---- rpmatfx.h ----
RwBool RpMatFXAtomicQueryEffects(RpAtomic *atomic);
RpMatFXMaterialFlags RpMatFXMaterialGetEffects(const RpMaterial *material);
RwTexture * RpMatFXMaterialGetEnvMapTexture(const RpMaterial *material);
RpMaterial * RpMatFXMaterialSetEffects(RpMaterial *material, RpMatFXMaterialFlags flags);
RpMaterial * RpMatFXMaterialSetEnvMapCoefficient(RpMaterial *material, RwReal coef);
RpMaterial * RpMatFXMaterialSetEnvMapFrame(RpMaterial *material, RwFrame *frame);
RwBool RpMatFXPluginAttach(void);

// ---- rpskin.h ----
RpAtomic * RpSkinAtomicSetHAnimHierarchy(RpAtomic *atomic, RpHAnimHierarchy *hierarchy);
RpAtomic * RpSkinAtomicSetType(RpAtomic *atomic, RpSkinType type);
RpSkin * RpSkinCreate(RwUInt32 numVertices, RwUInt32 numBones, RwMatrixWeights *vertexWeights, RwUInt32 *vertexIndices, RwMatrix *inverseMatrices);
RpGeometry * RpSkinGeometrySetSkin(RpGeometry *geometry, RpSkin *skin);
RwUInt32 RpSkinGetNumBones(RpSkin *skin);
const RwMatrix * RpSkinGetSkinToBoneMatrices(RpSkin *skin);
const RwUInt32 * RpSkinGetVertexBoneIndices(RpSkin *skin);
RwMatrixWeights* RpSkinGetVertexBoneWeights(RpSkin *skin);
RwBool RpSkinPluginAttach(void);

// ---- rpuvanim.h ----
RpMaterial * RpMaterialUVAnimAddAnimTime(RpMaterial *material, RwReal deltaTime);
RpMaterial * RpMaterialUVAnimApplyUpdate(RpMaterial *material);
RwBool RpMaterialUVAnimExists(const RpMaterial *material);
RwBool RpUVAnimPluginAttach(void);

// ---- rpworld.h ----
RpAtomic* RpAtomicClone(RpAtomic* atomic);
RpAtomic* RpAtomicCreate(void);
RwBool RpAtomicDestroy(RpAtomic* atomic);
RwInt32 RpAtomicRegisterPlugin(RwInt32 size, RwUInt32 pluginID, RwPluginObjectConstructor constructCB, RwPluginObjectDestructor destructCB, RwPluginObjectCopy copyCB);
RwInt32 RpAtomicRegisterPluginStream(RwUInt32 pluginID, RwPluginDataChunkReadCallBack readCB, RwPluginDataChunkWriteCallBack writeCB, RwPluginDataChunkGetSizeCallBack getSizeCB);
RpAtomic* RpAtomicSetFrame(RpAtomic* atomic, RwFrame* frame);
RpAtomic* RpAtomicSetGeometry(RpAtomic* atomic, RpGeometry* geometry, RwUInt32 flags);
RpClump* RpClumpAddAtomic(RpClump* clump, RpAtomic* atomic);
RpClump* RpClumpClone(RpClump* clump);
RpClump* RpClumpCreate(void);
RwBool RpClumpDestroy(RpClump* clump);
RpClump* RpClumpForAllAtomics(RpClump* clump, RpAtomicCallBack callback, void* data);
RwInt32 RpClumpGetNumAtomics(RpClump* clump);
void RpClumpGtaCancelStream();
RwInt32 RpClumpRegisterPlugin(RwInt32 size, RwUInt32 pluginID, RwPluginObjectConstructor constructCB, RwPluginObjectDestructor destructCB, RwPluginObjectCopy copyCB);
RwInt32 RpClumpRegisterPluginStream(RwUInt32 pluginID, RwPluginDataChunkReadCallBack readCB, RwPluginDataChunkWriteCallBack writeCB, RwPluginDataChunkGetSizeCallBack getSizeCB);
RpClump* RpClumpRemoveAtomic(RpClump* clump, RpAtomic* atomic);
RpClump* RpClumpRender(RpClump* clump);
RpClump* RpClumpStreamRead(RwStream* stream);
void RpD3D9GeometrySetUsageFlags(RpGeometry* geometry, RpD3D9GeometryUsageFlag flags);
RpGeometry* RpGeometryCreate(RwInt32 numVert, RwInt32 numTriangles, RwUInt32 format);
RwBool RpGeometryDestroy(RpGeometry* geometry);
RpGeometry* RpGeometryForAllMaterials(RpGeometry* geometry, RpMaterialCallBack fpCallBack, void* data);
RpGeometry* RpGeometryLock(RpGeometry* geometry, RwInt32 lockMode);
RwInt32 RpGeometryRegisterPlugin(RwInt32 size, RwUInt32 pluginID, RwPluginObjectConstructor constructCB, RwPluginObjectDestructor destructCB, RwPluginObjectCopy copyCB);
RwInt32 RpGeometryRegisterPluginStream(RwUInt32 pluginID, RwPluginDataChunkReadCallBack readCB, RwPluginDataChunkWriteCallBack writeCB, RwPluginDataChunkGetSizeCallBack getSizeCB);
RpMaterial* RpGeometryTriangleGetMaterial(const RpGeometry* geometry, const RpTriangle* triangle);
RpGeometry* RpGeometryTriangleSetMaterial(RpGeometry* geometry, RpTriangle* triangle, RpMaterial* material);
const RpGeometry* RpGeometryTriangleSetVertexIndices(const RpGeometry* geometry, RpTriangle* triangle, RwUInt16 vert1, RwUInt16 vert2, RwUInt16 vert3);
RpGeometry* RpGeometryUnlock(RpGeometry* geometry);
RpLight* RpLightCreate(RwInt32 type);
RwBool RpLightDestroy(RpLight* light);
RpLight* RpLightSetColor(RpLight* light, const RwRGBAReal* color);
RpLight* RpLightSetRadius(RpLight* light, RwReal radius);
RpMaterial* RpMaterialCreate();
RwBool RpMaterialDestroy(RpMaterial* material);
RwInt32 RpMaterialRegisterPlugin(RwInt32 size, RwUInt32 pluginID, RwPluginObjectConstructor constructCB, RwPluginObjectDestructor destructCB, RwPluginObjectCopy copyCB);
RwInt32 RpMaterialRegisterPluginStream(RwUInt32 pluginID, RwPluginDataChunkReadCallBack readCB, RwPluginDataChunkWriteCallBack writeCB, RwPluginDataChunkGetSizeCallBack getSizeCB);
RpMaterial* RpMaterialSetTexture(RpMaterial* material, RwTexture* texture);
const RpMorphTarget* RpMorphTargetCalcBoundingSphere(const RpMorphTarget* morphTarget, RwSphere* boundingSphere);
RpWorld* RpWorldAddCamera(RpWorld* world, RwCamera* camera);
RpWorld* RpWorldAddLight(RpWorld* world, RpLight* light);
RpWorld* RpWorldCreate(RwBBox* boundingBox);
RwBool RpWorldDestroy(RpWorld* world);
RwBool RpWorldPluginAttach();
RpWorld* RpWorldRemoveCamera(RpWorld* world, RwCamera* camera);
RpWorld* RpWorldRemoveLight(RpWorld* world, RpLight* light);
RxD3D9AllInOneInstanceCallBack RxD3D9AllInOneGetInstanceCallBack(RxPipelineNode* node);
RxD3D9AllInOneReinstanceCallBack RxD3D9AllInOneGetReinstanceCallBack(RxPipelineNode* node);
void RxD3D9AllInOneSetInstanceCallBack(RxPipelineNode* node, RxD3D9AllInOneInstanceCallBack callback);
void RxD3D9AllInOneSetReinstanceCallBack(RxPipelineNode* node, RxD3D9AllInOneReinstanceCallBack callback);
void RxD3D9AllInOneSetRenderCallBack(RxPipelineNode* node, RxD3D9AllInOneRenderCallBack callback);
RxNodeDefinition* RxNodeDefinitionGetD3D9AtomicAllInOne();
void _rpAtomicResyncInterpolatedSphere(RpAtomic* atomic);
RwInt32 _rpMaterialListAppendMaterial(RpMaterialList* matList, RpMaterial* material);
RpMaterialList* _rpMaterialListDeinitialize(RpMaterialList* matList);
RwInt32 _rpMaterialListFindMaterialIndex(const RpMaterialList* matList, const RpMaterial* material);
void _rwD3D9EnableClippingIfNeeded(void *object, RwUInt32 type);

// ---- rtanim.h ----
RtAnimAnimation * RtAnimAnimationCreate(RwInt32 typeID, RwInt32 numFrames, RwInt32 flags, RwReal duration);
RwBool RtAnimAnimationDestroy(RtAnimAnimation *animation);
RwBool RtAnimInitialize(void);
RwBool RtAnimInterpolatorSetCurrentAnim(RtAnimInterpolator *animI, RtAnimAnimation *anim);
RwBool RtAnimRegisterInterpolationScheme(RtAnimInterpolatorInfo *interpolatorInfo);

// ---- rtbmp.h ----
RwImage * RtBMPImageRead(const RwChar * imageName);

// ---- rtcharse.h ----
RwBool RtCharsetBufferFlush(void);
void RtCharsetClose(void);
RtCharset * RtCharsetCreate(const RwRGBA * foreGround, const RwRGBA * backGround);
RwBool RtCharsetDestroy(RtCharset * charSet);
RwBool RtCharsetOpen(void);
RtCharset * RtCharsetPrintBuffered(RtCharset * charSet, const RwChar * string, RwInt32 x, RwInt32 y, RwBool hideSpaces);

// ---- rtdict.h ----
RwBool RtDictDestroy(RtDict *dictionary);
RtDictSchema * RtDictSchemaSetCurrentDict(RtDictSchema *schema, RtDict *dict);
RtDict * RtDictSchemaStreamReadDict(RtDictSchema *schema, RwStream *stream);

// ---- rtpng.h ----
RwImage * RtPNGImageWrite(RwImage * image, const RwChar * imageName);

// ---- rtquat.h ----
RwBool RtQuatConvertFromMatrix(RtQuat * const qpQuat, const RwMatrix * const mpMatrix);
RtQuat * RtQuatRotate(RtQuat * quat, const RwV3d * axis, RwReal angle, RwOpCombineType combineOp);
RwV3d * RtQuatTransformVectors(RwV3d * vectorsOut, const RwV3d * vectorsIn, const RwInt32 numPoints, const RtQuat *quat);

// ---- rtslerp.h ----
void RtQuatSetupSlerpCache(RtQuat * qpFrom, RtQuat * qpTo, RtQuatSlerpCache * sCache);

// ---- rwcore.h ----
RwCamera * RwCameraBeginUpdate(RwCamera * camera);
RwCamera * RwCameraClear(RwCamera * camera, RwRGBA * colour, RwInt32 clearMode);
RwCamera * RwCameraCreate(void);
RwBool RwCameraDestroy(RwCamera * camera);
RwCamera * RwCameraEndUpdate(RwCamera * camera);
RwFrustumTestResult RwCameraFrustumTestSphere(const RwCamera * camera, const RwSphere * sphere);
RwCamera * RwCameraSetFarClipPlane(RwCamera *camera, RwReal farClip);
RwCamera * RwCameraSetNearClipPlane(RwCamera *camera, RwReal nearClip);
RwCamera * RwCameraSetProjection(RwCamera *camera, RwCameraProjection projection);
RwCamera * RwCameraSetViewWindow(RwCamera *camera, const RwV2d *viewWindow);
RwCamera * RwCameraShowRaster(RwCamera * camera, void *pDev, RwUInt32 flags);
RwBool RwD3D9CameraAttachWindow(void *camera, void *hwnd);
RwBool RwD3D9ChangeMultiSamplingLevels(RwUInt32 numLevels);
RwBool RwD3D9ChangeVideoMode(RwInt32 modeIndex);
RwBool RwD3D9DeviceSupportsDXTTexture(void);
RwBool RwD3D9EnableLight(RwInt32 index, RwBool enable);
RwUInt32 RwD3D9EngineGetMaxMultiSamplingLevels(void);
void RwD3D9EngineSetMultiSamplingLevels(RwUInt32 numLevels);
void RwD3D9EngineSetRefreshRate(RwUInt32 refreshRate);
const void * RwD3D9GetCaps(void);
void * RwD3D9GetCurrentD3DDevice(void);
void RwD3D9GetRenderState(RwUInt32 state, void *value);
RwBool RwD3D9SetLight(RwInt32 index, const void *light);
RwBool RwD3D9SetMaterial(const void *material);
void RwD3D9SetRenderState(RwUInt32 state, RwUInt32 value);
void RwD3D9SetStencilClear(RwUInt32 stencilClear);
RwBool RwD3D9SetSurfaceProperties(const RwSurfaceProperties *surfaceProps, const RwRGBA *color, RwUInt32 flags);
RwBool RwD3D9SetTexture(RwTexture *texture, RwUInt32 stage);
void RwD3D9SetTextureStageState(RwUInt32 stage, RwUInt32 type, RwUInt32 value);
RwBool RwD3D9SetTransform(RwUInt32 state, const void *matrix);
RwFrame * RwFrameAddChild(RwFrame * parent, RwFrame * child);
RwInt32 RwFrameCount(RwFrame * frame);
RwFrame * RwFrameCreate(void);
RwBool RwFrameDestroy(RwFrame * frame);
RwFrame * RwFrameForAllChildren(RwFrame * frame, RwFrameCallBack callBack, void *data);
RwFrame * RwFrameForAllObjects(RwFrame * frame, RwObjectCallBack callBack, void *data);
RwMatrix * RwFrameGetLTM(RwFrame * frame);
RwFrame * RwFrameOrthoNormalize(RwFrame * frame);
RwInt32 RwFrameRegisterPlugin(RwInt32 size, RwUInt32 pluginID, RwPluginObjectConstructor constructCB, RwPluginObjectDestructor destructCB, RwPluginObjectCopy copyCB);
RwInt32 RwFrameRegisterPluginStream(RwUInt32 pluginID, RwPluginDataChunkReadCallBack readCB, RwPluginDataChunkWriteCallBack writeCB, RwPluginDataChunkGetSizeCallBack getSizeCB);
RwFrame * RwFrameRemoveChild(RwFrame * child);
RwFrame * RwFrameRotate(RwFrame * frame, const RwV3d * axis, RwReal angle, RwOpCombineType combine);
RwFrame * RwFrameSetIdentity(RwFrame * frame);
RwFrame * RwFrameTransform(RwFrame * frame, const RwMatrix * m, RwOpCombineType combine);
RwFrame * RwFrameTranslate(RwFrame * frame, const RwV3d * v, RwOpCombineType combine);
RwFrame * RwFrameUpdateObjects(RwFrame * frame);
RwBool RwIm3DEnd(void);
RwBool RwIm3DRenderIndexedPrimitive(RwPrimitiveType primType, RwImVertexIndex *indices, RwInt32 numIndices);
RwBool RwIm3DRenderLine(RwInt32 vert1, RwInt32 vert2);
RwBool RwIm3DRenderPrimitive(RwPrimitiveType primType);
void * RwIm3DTransform(RwIm3DVertex *pVerts, RwUInt32 numVerts, RwMatrix *ltm, RwUInt32 flags);
RwImage * RwImageAllocatePixels(RwImage * image);
RwImage * RwImageCreate(RwInt32 width, RwInt32 height, RwInt32 depth);
RwBool RwImageDestroy(RwImage * image);
RwImage * RwImageFindRasterFormat(RwImage *ipImage,RwInt32 nRasterType, RwInt32 *npWidth,RwInt32 *npHeight, RwInt32 *npDepth,RwInt32 *npFormat);
RwImage * RwImageSetFromRaster(RwImage *image, RwRaster *raster);
RwUInt32 RwRGBAToPixel(RwRGBA * rgbIn, RwInt32 rasterFormat);
RwRaster * RwRasterCreate(RwInt32 width, RwInt32 height, RwInt32 depth, RwInt32 flags);
RwBool RwRasterDestroy(RwRaster * raster);
RwUInt8 * RwRasterLock(RwRaster * raster, RwUInt8 level, RwInt32 lockMode);
RwRaster * RwRasterPopContext(void);
RwRaster * RwRasterPushContext(RwRaster * raster);
RwRaster * RwRasterRenderFast(RwRaster * raster, RwInt32 x, RwInt32 y);
RwRaster * RwRasterSetFromImage(RwRaster *raster, RwImage *image);
RwRaster * RwRasterUnlock(RwRaster * raster);
RwRaster * RwRasterUnlockPalette(RwRaster * raster);
RwTexture * RwTexDictionaryAddTexture(RwTexDictionary * dict, RwTexture * texture);
RwTexDictionary * RwTexDictionaryCreate(void);
RwBool RwTexDictionaryDestroy(RwTexDictionary * dict);
RwTexture * RwTexDictionaryFindNamedTexture(RwTexDictionary * dict, const RwChar * name);
const RwTexDictionary * RwTexDictionaryForAllTextures(const RwTexDictionary * dict, RwTextureCallBack fpCallBack, void *pData);
RwTexDictionary * RwTexDictionaryGetCurrent(void);
RwInt32 RwTexDictionaryRegisterPlugin(RwInt32 size, RwUInt32 pluginID, RwPluginObjectConstructor constructCB, RwPluginObjectDestructor destructCB, RwPluginObjectCopy copyCB);
RwTexture * RwTexDictionaryRemoveTexture(RwTexture * texture);
RwTexDictionary * RwTexDictionarySetCurrent(RwTexDictionary * dict);
const RwTexDictionary * RwTexDictionaryStreamWrite(const RwTexDictionary *texDict, RwStream *stream);
RwTexture * RwTextureCreate(RwRaster * raster);
RwBool RwTextureDestroy(RwTexture * texture);
RwTextureCallBackFind RwTextureGetFindCallBack(void);
RwTexture * RwTextureRead(const RwChar * name, const RwChar * maskName);
RwBool RwTextureSetAutoMipmapping(RwBool enable);
RwBool RwTextureSetFindCallBack(RwTextureCallBackFind callBack);
RwBool RwTextureSetMipmapping(RwBool enable);
RwTexture * RwTextureSetName(RwTexture * texture, const RwChar * name);
RwTexture * RwTextureSetRaster(RwTexture * texture, RwRaster * raster);
RwBool RwTextureSetReadCallBack(RwTextureCallBackRead callBack);
RxLockedPipe * RxLockedPipeAddFragment(RxLockedPipe *pipeline, RwUInt32 *firstIndex, RxNodeDefinition *nodeDef0, ...);
RxPipeline * RxLockedPipeUnlock(RxLockedPipe *pipeline);
RxPipeline * RxPipelineCreate(void);
RxPipelineNode * RxPipelineFindNodeByName(RxPipeline *pipeline, const RwChar *name, RxPipelineNode *start, RwInt32 *nodeIndex);
RxLockedPipe * RxPipelineLock(RxPipeline *pipeline);
rwD3D9DeviceRestoreCallBack _rwD3D9DeviceGetRestoreCallback(void);
void _rwD3D9DeviceSetRestoreCallback(rwD3D9DeviceRestoreCallBack callback);
void _rwD3D9SetStreams(const RxD3D9VertexStream *streams, RwBool useOffsets);
RwFrame * _rwFrameCloneAndLinkClones(RwFrame * root);

// ---- rwplcore.h ----
RwBool RwEngineClose(void);
RwInt32 RwEngineGetCurrentSubSystem(void);
RwInt32 RwEngineGetCurrentVideoMode(void);
RwInt32 RwEngineGetNumSubSystems(void);
RwInt32 RwEngineGetNumVideoModes(void);
RwSubSystemInfo * RwEngineGetSubSystemInfo(RwSubSystemInfo *subSystemInfo, RwInt32 subSystemIndex);
RwUInt32 RwEngineGetVersion(void);
RwVideoMode * RwEngineGetVideoModeInfo(RwVideoMode *modeinfo, RwInt32 modeIndex);
RwBool RwEngineInit(const RwMemoryFunctions *memFuncs, RwUInt32 initFlags, RwUInt32 resArenaSize);
RwBool RwEngineOpen(RwEngineOpenParams *initParams);
RwBool RwEngineSetSubSystem(RwInt32 subSystemIndex);
RwBool RwEngineSetVideoMode(RwInt32 modeIndex);
RwBool RwEngineStart(void);
RwBool RwEngineStop(void);
RwBool RwEngineTerm(void);
RwMatrix * RwMatrixCreate(void);
RwBool RwMatrixDestroy(RwMatrix * mpMat);
RwMatrix * RwMatrixInvert(RwMatrix * matrixOut, const RwMatrix * matrixIn);
RwMatrix * RwMatrixMultiply(RwMatrix * matrixOut, const RwMatrix * MatrixIn1, const RwMatrix * matrixIn2);
RwMatrix * RwMatrixRotate(RwMatrix * matrix, const RwV3d * axis, RwReal angle, RwOpCombineType combineOp);
RwMatrix * RwMatrixScale(RwMatrix * matrix, const RwV3d * scale, RwOpCombineType combineOp);
RwMatrix * RwMatrixTransform(RwMatrix * matrix, const RwMatrix * transform, RwOpCombineType combineOp);
RwMatrix * RwMatrixTranslate(RwMatrix * matrix, const RwV3d * translation, RwOpCombineType combineOp);
RwMatrix * RwMatrixUpdate(RwMatrix * matrix);
RwBool RwStreamClose(RwStream * stream, void *pData);
RwBool RwStreamFindChunk(RwStream *stream, RwUInt32 type, RwUInt32 *lengthOut, RwUInt32 *versionOut);
RwStream * RwStreamOpen(RwStreamType type, RwStreamAccessType accessType, const void *pData);
RwUInt32 RwStreamRead(RwStream * stream, void *buffer, RwUInt32 length);
RwStream * RwStreamReadChunkHeaderInfo(RwStream *stream, RwChunkHeaderInfo *chunkHeaderInfo);
RwStream * RwStreamSkip(RwStream * stream, RwUInt32 offset);
RwStream * RwStreamWrite(RwStream * stream, const void *buffer, RwUInt32 length);
RwReal RwV2dLength(const RwV2d * in);
RwReal RwV3dLength(const RwV3d * in);
RwReal RwV3dNormalize(RwV3d * out, const RwV3d * in);
RwV3d * RwV3dTransformPoint(RwV3d * pointOut, const RwV3d * pointIn, const RwMatrix * matrix);
RwV3d * RwV3dTransformPoints(RwV3d * pointsOut, const RwV3d * pointsIn, RwInt32 numPoints, const RwMatrix * matrix);
RwV3d * RwV3dTransformVector(RwV3d * vectorOut, const RwV3d * vectorIn, const RwMatrix * matrix);
RwV3d * RwV3dTransformVectors(RwV3d * vectorsOut, const RwV3d * vectorsIn, RwInt32 numPoints, const RwMatrix * matrix);
RwStream * _rwStreamInitialize(RwStream *stream, RwBool rwOwned, RwStreamType type, RwStreamAccessType accessType, const void *pData);

// ---- rwtexdict.h ----
RwTexture* GetFirstTexture(RwTexDictionary* txd);
bool RpClumpGtaStreamRead1(RwStream* stream);
RpClump* RpClumpGtaStreamRead2(RwStream* stream);
RwTexDictionary* RwTexDictionaryGtaStreamRead(RwStream* stream);
RwTexDictionary* RwTexDictionaryGtaStreamRead1(RwStream* stream);
RwTexDictionary* RwTexDictionaryGtaStreamRead2(RwStream* stream, RwTexDictionary* txd);

