#pragma once

#define APP_CLASS "Grand theft auto San Andreas"

//! Win32 fail check (returns from function automagically)
#define WIN_FCHECK(x) do { \
        if (HRESULT hr = (x); FAILED(hr)) { \
	        NOTSA_LOG_DEBUG(TEXT("FAILED(hr=0x{:x}) in ") TEXT(#x) TEXT("\n"), (size_t)(hr)); \
            return; \
        } \
    } while (0) \

// Custom enum, generated by ChatGPT ~~thank you~~ - ChatGPT was wrong.
//
enum class WinVer {
    WIN_95,             //< Windows 95
    WIN_98,             //< Windows 98
    WIN_NT,             //< Windows NT
    WIN_2000_XP_2003,   //< Windows 2000/XP/Server 2003
    WIN_VISTA_OR_LATER, //< Windows Vista/7/8/10

    UNKNOWN
};

struct OSStatus {
    WinVer OSVer;
    DWORD  DxVer; // Always 0x900
    struct { // TODO: Just use MEMORYSTATUS stuct here
        SIZE_T TotalPhys;
        SIZE_T AvailPhys;
        SIZE_T TotalVirtual;
        SIZE_T AvailVirtual;
    } RAM;
    struct {
        SIZE_T Total;
        SIZE_T Avail;
    } VRAM;
};
NOTSA_GLOBAL_HDR_EXT(s_OSStatus, 0xC8CF68, (OSStatus), {});
static NOTSA_GLOBAL_ALIAS(s_WinVer, 0xC8CF68, (WinVer), *reinterpret_cast<WinVer*>(reinterpret_cast<uint8*>(&s_OSStatus) + 0));

NOTSA_GLOBAL_HDR_EXT(anisotropySupportedByGFX, 0xC87FFC, (bool), {});
NOTSA_GLOBAL_HDR_EXT(isForeground, 0xC920EC, (bool), {});
NOTSA_GLOBAL_HDR_EXT(Windowed, 0xC920CC, (bool), {});

void Win32InjectHooks();

BOOL GTATranslateShiftKey(RsKeyCodes*);
BOOL GTATranslateKey(RsKeyCodes* ck, LPARAM lParam, UINT vk);

#define IDI_MAIN_ICON                   1042
