#!/usr/bin/env python3
"""gen_strip_cases.py <gta_sa_compact.exe> <librw assets dir with vgsnbuild07.dff> <out.inc>
Runs the exe's tristrip generator (RpGeometryUnlock path: qsort 0x8247E0 + comparator 0x759640 + 0x7591D0 with the default method arguments (0,1))
under Unicorn (tools/standalone/strip_unicorn.py) on the test inputs and writes tests/standalone/rw_strip_cases.inc for rw_strip_test.cpp."""
import sys, struct, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import strip_unicorn as su

def lcg(s): return (s * 1103515245 + 12345) & 0x7fffffff
def shuffle(l, seed):
    s = seed
    for i in range(len(l) - 1, 0, -1):
        s = lcg(s); j = s % (i + 1); l[i], l[j] = l[j], l[i]
    return l
def grid(w, h, nm):
    t = []
    for y in range(h):
        for x in range(w):
            a = y * (w + 1) + x; b = a + 1; c = a + (w + 1); e = c + 1; m = (x // 4 + y // 3) % nm
            t += [(a, c, b, m), (b, c, e, m)]
    return t
def soup(n, nv, seed, nm):
    s = seed; t = []
    while len(t) < n:
        s = lcg(s); a = s % nv; s = lcg(s); b = s % nv; s = lcg(s); c = s % nv
        if len({a, b, c}) == 3: t.append((a, b, c, len(t) % nm))
    return t
def fan(n, m=0): return [(0, i + 1, i + 2, m) for i in range(n)]
def fnv(meshes):
    h = 0x811c9dc5
    def feed(v):
        nonlocal h
        for byte in struct.pack('<H', v): h = ((h ^ byte) * 0x01000193) & 0xffffffff
    for m, idx in meshes:
        feed(m); feed(len(idx))
        for v in idx: feed(v)
    return h

def dff_window(path):
    sys.path.insert(0, os.environ.get('DFFPY', '.'))
    import dff
    g = max(dff.geoms(path), key=len)
    for s in range(0, len(g) - 100):
        if len({t[3] for t in g[s:s + 100]}) >= 3: break
    w = g[s:s + 100]; mm = {}
    for t in w: mm.setdefault(t[3], len(mm))
    return [(a, b, c, mm[m]) for a, b, c, m in w]

exe, assets, outp = sys.argv[1:4]
d, secs = su.load(exe)
cases = []   # (name, explicit?, tris, alphas, params)
cases.append(('grid 4x3, one material', 1, grid(4, 3, 1), [255]))
cases.append(('fan of 7 + isolated triangle + duplicate triangle', 1, fan(7) + [(20, 21, 22, 0), (0, 1, 2, 0)], [255]))
cases.append(('soup 24 triangles / 10 vertices, 2 materials (one translucent)', 1, soup(24, 10, 7, 2), [255, 128]))
sh = shuffle(grid(9, 6, 3), 99)
cases.append(('grid 9x6 shuffled, 3 materials (middle one translucent)', 1, sh, [255, 100, 255]))
cases.append(('vgsnbuild07.dff window of 100 triangles', 1, dff_window(os.path.join(assets, 'vgsnbuild07.dff')), None))
big1 = shuffle(grid(30, 20, 3), 5)
cases.append(('grid 30x20 shuffled, 3 materials [formula 0]', 0, big1, [255, 255, 90]))
big2 = soup(800, 200, 11, 1)
cases.append(('soup 800 triangles / 200 vertices [formula 1]', 0, big2, [255]))
runs = []
for name, explicit, tris, al in cases:
    nm = max(t[3] for t in tris) + 1
    al = al or [255] * nm
    runs.append(dict(tris=tris, mats=al, tryAll=0, pad=1))
res = su.run_cases(d, secs, runs, True)
o = ['// generated by tools/standalone/gen_strip_cases.py from the exe (0x7591D0 + qsort 0x8247E0 + comparator 0x759640) running under Unicorn; do not edit', '']
for i, ((name, explicit, tris, al), r, run) in enumerate(zip(cases, res, runs)):
    al = run['mats']
    nv = max(max(t[:3]) for t in tris) + 1
    tot = sum(len(m[1]) for m in r)
    o.append('// %s' % name)
    if explicit:
        o.append('static const uint16_t kTris%d[] = {%s};' % (i, ','.join('%d,%d,%d,%d' % t for t in tris)))
        o.append('static const uint16_t kExp%d[] = {%s};' % (i, ','.join('%d,%d,%s' % (m, len(idx), ','.join(map(str, idx))) for m, idx in r)))
    o.append('static const uint8_t kAlpha%d[] = {%s};' % (i, ','.join(map(str, al))))
o.append('static const StripCase kCases[] = {')
for i, ((name, explicit, tris, al), r, run) in enumerate(zip(cases, res, runs)):
    al = run['mats']; nv = max(max(t[:3]) for t in tris) + 1; tot = sum(len(m[1]) for m in r)
    kind = 0 if explicit else (1 if 'formula 0' in name else 2)
    # kind: 0 = explicit arrays, 1 = grid(30,20,3) shuffled(5), 2 = soup(800,200,11,1)
    o.append('    {"%s", %d, %d, %d, kAlpha%d, %d, %s, %d, %s, %d, %du},' % (
        name, kind, nv, len(al), i, len(tris), ('kTris%d' % i) if explicit else 'nullptr', len(r), ('kExp%d' % i) if explicit else 'nullptr', tot, fnv(r)))
o.append('};')
open(outp, 'w').write('\n'.join(o) + '\n')
for (name, *_), r in zip(cases, res): print(name, [(m, len(i)) for m, i in r])
