#!/usr/bin/env python3
"""Regenerates source/fakerw/rwenums.h from the game's own RenderWare headers (source/game_sa/RenderWare/rw/*.h).

The enum VALUES of the RW C API are part of the game's behaviour (they are compared, stored and passed around), so the type layer keeps the
original numbering and the shim maps them to librw's numbering at the call boundary. This script only extracts enum bodies / numeric chunk-id
macros verbatim; run it from the repo root:  python3 tools/standalone/gen_fakerw_enums.py
"""
import re, pathlib, sys

root = pathlib.Path(__file__).resolve().parents[2]
rwdir = root / 'source/game_sa/RenderWare/rw'
out = root / 'source/fakerw/rwenums.h'

ENUMS = """
RwPluginVendor RwCorePluginID RwPlatformID RwTextureCoordinateIndex RwPlaneType
RwStreamType RwStreamAccessType RwOpCombineType RwMatrixType RwMatrixFlag RwMatrixOptimizations
RwRenderState RwShadeMode RwTextureFilterMode RwFogType RwBlendFunction RwTextureAddressMode
RwStencilOperation RwStencilFunction RwAlphaTestFunction RwCullMode RwPrimitiveType RwVideoModeFlag RwEngineInitFlag RwDebugType RwEngineStatus
RwRasterLockMode RwRasterFlipMode RwRasterType RwRasterFormat RwRasterPrivateFlag RwImageFlag RwIm3DTransformFlags RwTextureStreamFlags
RwCameraClearMode RwCameraProjection RwFrustumTestResult RwClipFlag RxGeometryFlag
RpMeshHeaderFlags RpGeometryFlag RpGeometryLockMode RpLightType RpLightFlag RpInterpolatorFlag RpAtomicFlag RpAtomicSetGeomFlag
RpWorldFlag RpD3D9GeometryUsageFlag RpHAnimHierarchyFlag RpMatFXMaterialFlags RpSkinType RpUVAnimKeyFrameType
""".split()
MACROS_FROM = {'rwplcore.h': r'^\s*#\s*define\s+(MAKECHUNKID|GETOBJECTID|GETVENDORID)\b.*$',
               'rpcriter.h': r'^\s*#\s*define\s+rwID_\w+.*(?:\\\n.*)*$'}

def strip(t):
    t = re.sub(r'/\*.*?\*/', '', t, flags=re.S)
    return re.sub(r'//[^\n]*', '', t)

texts = {p.name: p.read_text(errors='ignore') for p in rwdir.glob('*.h')}
res = ['// GENERATED by tools/standalone/gen_fakerw_enums.py from source/game_sa/RenderWare/rw/*.h -- do not edit by hand.',
       '// RW C-API enums with the ORIGINAL RenderWare 3.6 numbering (game code relies on the values); the shim maps them to librw where it differs.',
       '#pragma once', '', '#ifndef RWFORCEENUMSIZEINT', '#define RWFORCEENUMSIZEINT ((int)((~((unsigned)0)) >> 1))', '#endif', '']
for fname, rx in MACROS_FROM.items():
    for m in re.finditer(rx, strip(texts[fname]), re.M):
        res.append(re.sub(r'\s*\\\n\s*', ' ', m.group(0)).strip())
    res.append('')
# every object-like #define of the RW headers (for macros that enumerators refer to, e.g. rpLIGHTPOSITIONINGSTART)
objmacros = {}
for fname, t in texts.items():
    for m in re.finditer(r'^\s*#\s*define\s+(\w+)[ \t]+([^\n]*?)\s*$', strip(t), re.M):
        objmacros.setdefault(m.group(1), m.group(0).strip())
emitted = set()
def emit_macros_for(body):
    for ident in re.findall(r'[A-Za-z_]\w*', body):
        if ident in objmacros and ident not in emitted and not re.match(r'(rwID_|MAKECHUNKID|RWFORCEENUMSIZEINT)', ident):
            emitted.add(ident)
            emit_macros_for(objmacros[ident].split(None, 2)[2] if len(objmacros[ident].split(None, 2)) > 2 else '')
            res.append('#ifndef ' + ident)
            res.append(objmacros[ident])
            res.append('#endif')
missing = []
for n in ENUMS:
    for fname, t in texts.items():
        m = re.search(r'\benum\s+' + n + r'\s*\{([^}]*)\}\s*;', strip(t))
        if m:
            body = re.sub(r'\n\s*\n', '\n', m.group(1)).rstrip()
            emit_macros_for(body)
            res.append(f'enum {n} {{{body}\n}};\ntypedef enum {n} {n};\n')
            break
    else:
        missing.append(n)
out.write_text('\n'.join(res))
print('wrote', out, 'missing:', missing)
