#!/usr/bin/env python3
"""Regenerates source/fakerw/rwapi.h: declarations (NO bodies) of the RenderWare C functions the game calls, with the exact signatures of
the original RW 3.6 headers (source/game_sa/RenderWare/rw/*.h). The bodies are written module by module in source/standalone/rw/*.cpp
(P2B-01 ...); a function that is declared here but not yet implemented is a link error, which is intended.

Names that are macros in the original headers, or are hand-written in rwaccessors.h / rwapi_extra.h, are listed in HAND and skipped here.
Run from the repo root:  python3 tools/standalone/gen_fakerw_api.py
"""
import re, pathlib, collections

root = pathlib.Path(__file__).resolve().parents[2]
src = root / 'source'
rwdir = src / 'game_sa/RenderWare/rw'
out = src / 'fakerw/rwapi.h'

# hand-written elsewhere (accessors / game-owned shapes); the generator must not declare them
HAND = set("""
RpSkinGeometryGetSkin RpSkinAtomicGetHAnimHierarchy
""".split())

def strip(t):
    t = re.sub(r'/\*.*?\*/', '', t, flags=re.S)
    return re.sub(r'//[^\n]*', '', t)

def statements(t):
    t = strip(t)
    t = re.sub(r'\\\n', '  ', t)
    t = re.sub(r'^[ \t]*#[^\n]*$', '', t, flags=re.M)
    t = re.sub(r'extern\s+"C"\s*\{', '', t)
    res, cur, depth = [], '', 0
    for ch in t:
        if ch == '{': depth += 1
        elif ch == '}': depth = max(0, depth - 1)
        cur += ch
        if ch == ';' and depth == 0:
            res.append(cur.strip()); cur = ''
    return res

protos = {}
macros = set()
for p in sorted(rwdir.glob('*.h')):
    text = p.read_text(errors='ignore')
    for m in re.finditer(r'^[ \t]*#\s*define\s+([A-Za-z_]\w*)', strip(text), re.M):
        macros.add(m.group(1))
    for s in statements(text):
        s = re.sub(r'\s+', ' ', s).rstrip(';').lstrip('} ').strip()
        s = re.sub(r',\s*\w+ \*__va_end__=NULL', ', ...', s)   # RxLockedPipeAddFragment: the repo's header spelled the C varargs as a defaulted pointer
        if '{' in s or s.startswith('typedef'): continue
        m = re.match(r'^(?:extern\s+)?(.+?)\s*\b([A-Za-z_]\w*)\s*\((.*)\)$', s)
        if m and not m.group(1).startswith(('return', 'if')):
            protos.setdefault(m.group(2), (m.group(1).strip(), m.group(3).strip(), p.name))

tok = re.compile(r'\b((?:Rw|Rp|Rt|Rx|_rw|_rp|_rx)[A-Za-z0-9_]*|GetFirstTexture|GetFirstTextureCallback)\b')
used = collections.Counter()
for dp in src.rglob('*'):
    if not dp.is_file() or dp.suffix not in ('.h', '.cpp', '.hpp', '.c', '.inc'): continue
    rel = dp.relative_to(src).as_posix()
    if rel.startswith(('game_sa/RenderWare/rw/', 'fakerw/', 'standalone/')): continue
    for m in tok.finditer(strip(dp.read_text(errors='ignore'))): used[m.group(1)] += 1

names = sorted(n for n in used if n in protos and n not in macros and n not in HAND)
byfile = collections.defaultdict(list)
for n in names: byfile[protos[n][2]].append(n)
res = ['// GENERATED by tools/standalone/gen_fakerw_api.py from source/game_sa/RenderWare/rw/*.h -- do not edit by hand.',
       '// Declarations of the RW C functions the game calls (exact RW 3.6 signatures); bodies: source/standalone/rw/*.cpp (P2B-01 ... 09).',
       '#pragma once', '']
for f in sorted(byfile):
    res.append(f'// ---- {f} ----')
    for n in byfile[f]:
        ret, args, _ = protos[n]
        res.append(f'{ret} {n}({args});')
    res.append('')
out.write_text('\n'.join(res) + '\n')
print(f'{len(names)} functions -> {out.relative_to(root)}')
