#!/usr/bin/env python3
"""quat_unicorn.py - runs the exe's quaternion / key-frame float code under Unicorn with the x87 precision control at 24 bits (what the game runs with after
RwEngineStart) and writes tests/standalone/rw_quat_cases.inc: random inputs + the exe's exact output bits, checked by rw_rtanim_rtquat_test /
rw_skin_hanim_test against the shim (RtQuat*, RpHAnimKeyFrame*, RtAnimBlend-style UnitConvertToMatrix).
Functions: RtQuatConvertFromMatrix 0x7EB5C0, RtQuatRotate 0x7EB7C0, RtQuatTransformVectors 0x7EBBB0, RtQuatSetupSlerpCache 0x7EC220,
RpHAnimKeyFrameBlend 0x7C60C0 / Add 0x7C6720 / MulRecip 0x7C65C0, RtAnimBlendKeyFrameApply 0x4D5FA0 (inlined RtQuatUnitConvertToMatrix).
Deliberate substitutions: RwSqrt 0x7EDB30 (table based in the exe) -> x87 fsqrt (= the shim's exact sqrtf); RwV3dNormalize 0x7ED9B0 -> not needed
(RtQuatRotate cases use axes whose squared length is exactly 1).
Usage: python tools/standalone/quat_unicorn.py gta_sa_compact.exe tests/standalone/rw_quat_cases.inc"""
import sys, struct, random, math
from unicorn import Uc, UC_ARCH_X86, UC_MODE_32, UC_HOOK_CODE
from unicorn.x86_const import UC_X86_REG_ESP, UC_X86_REG_EAX, UC_X86_REG_EIP, UC_X86_REG_FPCW

BASE, END = 0x400000, 0xcb1000
STACK, SENT, BUF = 0x2000000, 0x6000000, 0x7000000

def load(path):
    d = open(path, 'rb').read()
    secs = [(0x401000, 0x400, 0x456400), (0x858000, 0x456800, 0x4A1C00 - 0x456800), (0x8A4000, 0x4A1C00, 0x40000)]
    img = bytearray(END - BASE)
    for va, raw, sz in secs:
        img[va - BASE:va - BASE + sz] = d[raw:raw + sz]
    # RwSqrt 0x7EDB30 -> fld dword [esp+4]; fsqrt; ret
    img[0x7edb30 - BASE:0x7edb30 - BASE + 7] = bytes.fromhex('d9442404d9fac3')
    # RwV3dNormalize 0x7ED9B0 (table based, the table is built at engine start) -> copy for axes of squared length exactly 1 (see hook below); fld1; ret
    img[0x7ed9b0 - BASE:0x7ed9b0 - BASE + 3] = bytes.fromhex('d9e8c3')
    return bytes(img)

def make_uc(img, fpcw=0x007f):
    uc = Uc(UC_ARCH_X86, UC_MODE_32)
    uc.mem_map(BASE, END - BASE); uc.mem_write(BASE, img)
    for a, n in ((STACK, 0x100000), (SENT, 0x1000), (BUF, 0x10000)):
        uc.mem_map(a, n)
    uc.mem_write(SENT, b'\xf4' * 16)
    uc.reg_write(UC_X86_REG_FPCW, fpcw)
    def h_norm(uc, address, size, user):
        esp = uc.reg_read(UC_X86_REG_ESP)
        out, inp = struct.unpack('<II', uc.mem_read(esp + 4, 8))
        v = struct.unpack('<3f', uc.mem_read(inp, 12))
        assert v[0] * v[0] + v[1] * v[1] + v[2] * v[2] == 1.0, v
        uc.mem_write(out, struct.pack('<3f', *v))
    uc.hook_add(UC_HOOK_CODE, h_norm, begin=0x7ed9b0, end=0x7ed9b0)
    return uc

def call(uc, addr, args):
    """cdecl call; args = list of 32-bit ints"""
    esp = STACK + 0x80000 - 64
    uc.mem_write(esp, struct.pack('<%dI' % (len(args) + 1), SENT, *args))
    uc.reg_write(UC_X86_REG_ESP, esp)
    try:
        uc.emu_start(addr, SENT, count=100000)
    except Exception as e:
        raise RuntimeError('call %x failed at eip=%x: %s' % (addr, uc.reg_read(UC_X86_REG_EIP), e))

def fb(f): return struct.unpack('<I', struct.pack('<f', float(f)))[0]
def bf(u): return struct.unpack('<f', struct.pack('<I', u))[0]

def rand_unit_quat(rng):
    q = [rng.gauss(0, 1) for _ in range(4)]
    n = math.sqrt(sum(x * x for x in q))
    return [x / n for x in q]

def quat_to_mat(q):  # q = x y z w ; returns 3x3 rows right/up/at (RW convention, images of basis vectors)
    x, y, z, w = q
    return [[1 - 2 * (y * y + z * z), 2 * (x * y + z * w), 2 * (x * z - y * w)],
            [2 * (x * y - z * w), 1 - 2 * (x * x + z * z), 2 * (y * z + x * w)],
            [2 * (x * z + y * w), 2 * (y * z - x * w), 1 - 2 * (x * x + y * y)]]

def gen(exe, out):
    img = load(exe)
    rng = random.Random(0x5a5a)
    lines = ['// generated by tools/standalone/quat_unicorn.py from the exe running under Unicorn (x87 PC=24); do not edit', '']
    def emit(name, rows, width):
        lines.append('static const uint32_t %s[][%d] = {' % (name, width))
        for r in rows: lines.append('  {' + ','.join('0x%08xu' % v for v in r) + '},')
        lines.append('};')
        lines.append('')

    # ---- ConvertFromMatrix: in = 12 floats (right.xyz up.xyz at.xyz as 3 rows) -> out 4 floats (x y z w)
    rows = []
    qs = [rand_unit_quat(rng) for _ in range(250)]
    # force every branch: 180 degree rotations about axes near x, y, z
    for ax in range(3):
        for _ in range(30):
            v = [rng.gauss(0, .15) for _ in range(3)]; v[ax] = 1.0 + rng.gauss(0, .05)
            n = math.sqrt(sum(a * a for a in v)); ang = math.pi * (0.8 + 0.2 * rng.random())
            s = math.sin(ang / 2); qs.append([v[0] / n * s, v[1] / n * s, v[2] / n * s, math.cos(ang / 2)])
    qs += [[0, 0, 0, 1], [1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0.5, 0.5, 0.5, 0.5], [-0.5, 0.5, -0.5, 0.5]]
    for q in qs:
        m = quat_to_mat(q)
        uc = make_uc(img)
        mat = struct.pack('<16f', m[0][0], m[0][1], m[0][2], 0, m[1][0], m[1][1], m[1][2], 0, m[2][0], m[2][1], m[2][2], 0, 0, 0, 0, 0)
        uc.mem_write(BUF + 0x100, mat); uc.mem_write(BUF, b'\xcc' * 16)
        call(uc, 0x7eb5c0, [BUF, BUF + 0x100])
        o = struct.unpack('<4I', uc.mem_read(BUF, 16))
        inw = struct.unpack('<16I', mat)
        rows.append([inw[0], inw[1], inw[2], inw[4], inw[5], inw[6], inw[8], inw[9], inw[10], o[0], o[1], o[2], o[3]])  # out: imag.x imag.y imag.z real
    emit('kConvFromMat', rows, 13)

    # ---- TransformVectors: quat (x y z w, not nec. unit) + 3 vectors -> 3 vectors
    rows = []
    for i in range(120):
        q = rand_unit_quat(rng) if i % 3 else [rng.gauss(0, 1.5) for _ in range(4)]
        vs = [[rng.uniform(-50, 50) for _ in range(3)] for _ in range(3)]
        uc = make_uc(img)
        qb = struct.pack('<4f', *q)  # RtQuat = imag.xyz, real
        uc.mem_write(BUF + 0x100, struct.pack('<9f', *[c for v in vs for c in v])); uc.mem_write(BUF + 0x200, qb); uc.mem_write(BUF, b'\xcc' * 64)
        call(uc, 0x7ebbb0, [BUF, BUF + 0x100, 3, BUF + 0x200])
        o = struct.unpack('<9I', uc.mem_read(BUF, 36))
        rows.append(list(struct.unpack('<4I', qb)) + list(struct.unpack('<9I', uc.mem_read(BUF + 0x100, 36))) + list(o))
    emit('kTransformVec', rows, 22)

    # ---- SetupSlerpCache: from/to quats -> cache (raFrom 4, raTo 4, omega, nearlyZero)
    rows = []
    def pair(kind):
        a = rand_unit_quat(rng)
        if kind == 0:  b = rand_unit_quat(rng)
        elif kind == 1:   # tiny angle (dot ~ 1)
            b = [a[i] + rng.gauss(0, 1e-3) for i in range(4)]; n = math.sqrt(sum(x * x for x in b)); b = [x / n for x in b]
        elif kind == 2:   # dot around +-0.5 boundary
            while True:
                b = rand_unit_quat(rng); d = sum(x * y for x, y in zip(a, b))
                if abs(abs(d) - 0.5) < 0.05: break
        elif kind == 3:   # dot near -1
            b = [-a[i] + rng.gauss(0, 1e-3) for i in range(4)]; n = math.sqrt(sum(x * x for x in b)); b = [x / n for x in b]
        elif kind == 4: b = list(a)
        elif kind == 5: b = [-x for x in a]
        elif kind == 6: b = [a[i] + rng.gauss(0, 1e-6) for i in range(4)]
        else: b = [x * 1.0001 for x in rand_unit_quat(rng)]   # non unit: dot may exceed 1
        return a, b
    for i in range(400):
        a, b = pair(i % 8)
        uc = make_uc(img)
        uc.mem_write(BUF + 0x100, struct.pack('<4f', *a)); uc.mem_write(BUF + 0x110, struct.pack('<4f', *b)); uc.mem_write(BUF, b'\xcc' * 64)
        call(uc, 0x7ec220, [BUF + 0x100, BUF + 0x110, BUF])
        o = struct.unpack('<10I', uc.mem_read(BUF, 40))
        rows.append(list(struct.unpack('<4I', uc.mem_read(BUF + 0x100, 16))) + list(struct.unpack('<4I', uc.mem_read(BUF + 0x110, 16))) + list(o))
    emit('kSlerpCache', rows, 18)

    # ---- Rotate (angle in degrees, axis: canonical) for REPLACE(0) PRECONCAT(1) POSTCONCAT(2)
    rows = []
    axes = [(1, 0, 0), (0, 1, 0), (0, 0, 1), (-1, 0, 0), (0, -1, 0), (0, 0, -1)]
    for i in range(240):
        q = rand_unit_quat(rng); ax = axes[i % 6]; ang = rng.uniform(-400, 400); op = (i // 6) % 3
        uc = make_uc(img)
        uc.mem_write(BUF, struct.pack('<4f', *q)); uc.mem_write(BUF + 0x100, struct.pack('<3f', *ax))
        call(uc, 0x7eb7c0, [BUF, BUF + 0x100, fb(ang), op])
        rows.append(list(struct.unpack('<4I', struct.pack('<4f', *q))) + [fb(ax[0]), fb(ax[1]), fb(ax[2]), fb(ang), op] + list(struct.unpack('<4I', uc.mem_read(BUF, 16))))
    emit('kRotate', rows, 13)

    # ---- hanim key frame callbacks on 36-byte frames {prev, time, q(x y z w), t(x y z)}
    def kf():
        q = rand_unit_quat(rng); return [0, fb(rng.uniform(0, 3))] + [fb(c) for c in q] + [fb(rng.uniform(-3, 3)) for _ in range(3)]
    def put(uc, addr, fr): uc.mem_write(addr, struct.pack('<9I', *fr))
    rows = []
    for i in range(400):
        f1, f2 = kf(), kf()
        if i % 5 == 0:    # nearly identical rotations -> linear branch
            f2[2:6] = [fb(bf(f1[2 + k]) + rng.gauss(0, 1e-3)) for k in range(4)]
        if i % 7 == 0:    # opposite hemisphere
            f2[2:6] = [fb(-bf(f2[2 + k])) for k in range(4)]
        if i % 11 == 0:   # identical
            f2[2:6] = list(f1[2:6])
        alpha = [0.0, 1.0, 0.5, rng.random(), rng.random(), 1e-4, 0.9999][i % 7]
        uc = make_uc(img)
        put(uc, BUF + 0x100, f1); put(uc, BUF + 0x200, f2); put(uc, BUF, [0xcccccccc] * 9)
        call(uc, 0x7c60c0, [BUF, BUF + 0x100, BUF + 0x200, fb(alpha)])
        rows.append(f1 + f2 + [fb(alpha)] + list(struct.unpack('<9I', uc.mem_read(BUF, 36))) + list(struct.unpack('<9I', uc.mem_read(BUF + 0x200, 36))))
    emit('kBlend', rows, 37)
    rows = []
    for i in range(150):
        f1, f2 = kf(), kf()
        uc = make_uc(img); put(uc, BUF + 0x100, f1); put(uc, BUF + 0x200, f2); put(uc, BUF, [0xcccccccc] * 9)
        call(uc, 0x7c6720, [BUF, BUF + 0x100, BUF + 0x200])
        rows.append(f1 + f2 + list(struct.unpack('<9I', uc.mem_read(BUF, 36))))
    emit('kAdd', rows, 27)
    rows = []
    for i in range(150):
        f, s = kf(), kf()
        if i % 10 == 0: s[2:6] = [0, 0, 0, 0]
        else:
            s[2:6] = [fb(bf(x) * (0.5 + rng.random())) for x in s[2:6]]
        uc = make_uc(img); put(uc, BUF + 0x100, f); put(uc, BUF + 0x200, s)
        # the zero-norm case reads an uninitialised stack slot in the exe: pre-fill it with 0 so the result is deterministic (the shim uses 0)
        uc.mem_write(STACK + 0x80000 - 64 - 0x20 - 8, b'\0' * 64)
        call(uc, 0x7c65c0, [BUF + 0x100, BUF + 0x200])
        rows.append(f + s + list(struct.unpack('<9I', uc.mem_read(BUF + 0x100, 36))))
    emit('kMulRecip', rows, 27)

    # ---- RtAnimBlendKeyFrameApply 0x4D5FA0(matrix, frame): inlined RtQuatUnitConvertToMatrix; frame = RpHAnimBlendInterpFrame {q (x y z w), t}
    rows = []
    for i in range(200):
        q = rand_unit_quat(rng) if i % 4 else [rng.gauss(0, 1), rng.gauss(0, 1), rng.gauss(0, 1), rng.gauss(0, 1)]
        t = [rng.uniform(-5, 5) for _ in range(3)]
        uc = make_uc(img)
        uc.mem_write(BUF + 0x100, struct.pack('<7f', *q, *t)); uc.mem_write(BUF, b'\xcc' * 64)
        call(uc, 0x4d5fa0, [BUF, BUF + 0x100])
        o = struct.unpack('<16I', uc.mem_read(BUF, 64))
        rows.append([fb(c) for c in q] + [o[0], o[1], o[2], o[3], o[4], o[5], o[6], o[7], o[8], o[9], o[10], o[11], o[12], o[13], o[14], o[15]])
    emit('kUnitToMat', rows, 20)

    # ---- RtQuatSlerp macro as inlined in BoneNode_c::BlendKeyframe 0x616E30 (thiscall: ecx = node {+0xC: interp frame ptr (q at +0), +0x10: m_Orientation}, blend on the stack)
    rows = []
    for i in range(400):
        a, b = pair(i % 8)
        blend = [0.5, rng.random(), 1e-3, 0.999, 0.25, 0.75][i % 6]
        uc = make_uc(img)
        uc.mem_write(BUF + 0x400, struct.pack('<4f', *a))            # interp frame (q)
        node = struct.pack('<3I', 0, 0, 0) + struct.pack('<I', BUF + 0x400) + struct.pack('<4f', *b)
        uc.mem_write(BUF + 0x200, node)
        esp = STACK + 0x80000 - 64
        uc.mem_write(esp, struct.pack('<If', SENT, blend))
        uc.reg_write(UC_X86_REG_ESP, esp)
        from unicorn.x86_const import UC_X86_REG_ECX
        uc.reg_write(UC_X86_REG_ECX, BUF + 0x200)
        uc.emu_start(0x616e30, SENT, count=100000)
        rows.append(list(struct.unpack('<4I', struct.pack('<4f', *a))) + list(struct.unpack('<4I', struct.pack('<4f', *b))) + [fb(blend)] + list(struct.unpack('<4I', uc.mem_read(BUF + 0x400, 16))))
    emit('kBoneBlend', rows, 13)

    # ---- RtQuatConvertToMatrix as inlined in CPhysical::PositionAttachedEntity: [0x5471CF, 0x547352) with esi = entity (quaternion x y z w at +0x118), result matrix at esp+0x90
    from unicorn.x86_const import UC_X86_REG_ESI
    rows = []
    for i in range(200):
        q = rand_unit_quat(rng) if i % 4 else [rng.gauss(0, 1), rng.gauss(0, 1), rng.gauss(0, 1), rng.gauss(0, 1)]
        uc = make_uc(img)
        ent = BUF + 0x1000
        uc.mem_write(ent + 0x118, struct.pack('<4f', *q))
        esp = STACK + 0x80000 - 0x400
        uc.mem_write(esp, b'\xcc' * 0x200)
        uc.reg_write(UC_X86_REG_ESP, esp); uc.reg_write(UC_X86_REG_ESI, ent)
        uc.emu_start(0x5471cf, 0x547352, count=100000)
        m = struct.unpack('<16I', uc.mem_read(esp + 0x90, 64))
        rows.append([fb(c) for c in q] + [m[0], m[1], m[2], m[3], m[4], m[5], m[6], m[8], m[9], m[10], m[12], m[13], m[14]])
    emit('kQuatToMat', rows, 17)

    open(out, 'w').write('\n'.join(lines) + '\n')

if __name__ == '__main__':
    gen(sys.argv[1], sys.argv[2])
