#!/usr/bin/env python3
"""Generates rw_exe_oracle_fixups.inc for tests/standalone/rw_math_stream_test.cpp (the exe-oracle part).

The oracle runs the REAL RW 3.6 machine code of gta_sa_compact.exe inside the test process. Wine cannot give the test the exe's own address range
(0x400000.. is taken by the loader), so two windows of the exe's .text are copied to the heap and every absolute address they contain is rebased:
  * operands pointing into .text (function pointers stored by the plugin constructors) -> kind 1: + (window copy - window VA)
  * operands pointing into .rdata/.data/.bss (floats, the RwEngineInstance pointer, plugin offsets) -> kind 0: + (data copy - 0x858000)
Relative call/jmp/jcc displacements inside a window stay valid because each window is copied contiguously. Only the fixup OFFSETS are generated
here; no bytes of the exe are stored in the repository (the test reads the code from the exe at run time).

usage: python3 -I gen_oracle_fixups.py <gta_sa_compact.exe> <capstone-enabled python> > rw_exe_oracle_fixups.inc   (run with that python itself)
"""
import sys
from capstone import *
from capstone.x86 import *

exe = open(sys.argv[1], 'rb').read()
# code windows that the oracle executes (disassembled for the fixups); the whole span between the first and the last is copied contiguously so that
# relative calls/jumps between windows stay valid:
#   0x749330 RpAtomicGetWorldBoundingSphere, 0x74C200 RpMorphTargetCalcBoundingSphere, 0x7EB5C0 rtquat, 0x7ED5F0 vector/sqrt plugin, 0x7EE200 camera
#   (zscale, sync 0x7EE5A0, clip builders), 0x7F0000 frame routines + 0x7F12F0 matrix routines, 0x808F60 bbox, 0x809550 frame sync
WINDOWS = [(0x749330, 0x749480), (0x74C200, 0x74C310), (0x7EB5C0, 0x7EC800), (0x7ED5F0, 0x7EE0C0), (0x7EE200, 0x7EF3B0), (0x7F0000, 0x7F2720),
           (0x808F60, 0x809020), (0x809550, 0x809900)]
SPAN = (WINDOWS[0][0], WINDOWS[-1][1])
TEXT = (0x401000, 0x858000); DATA = (0x858000, 0xCB0000)

def raw(va): return va - 0x401000 + 0x400

md = Cs(CS_ARCH_X86, CS_MODE_32); md.detail = True
print("// generated by tests/standalone/tools/gen_oracle_fixups.py - rebasing fixups of the exe code span used by the oracle in rw_math_stream_test.cpp")
print("static const unsigned kSpanVA = 0x%X, kSpanSize = 0x%X;" % (SPAN[0], SPAN[1] - SPAN[0]))
print("static const unsigned kFix[][2] = {")
for (lo, hi) in WINDOWS:
    code = exe[raw(lo):raw(hi)]
    def insns(code, base):
        # capstone stops at the first undecodable byte (alignment filler, data): skip it and continue
        off = 0
        while off < len(code):
            last = off
            for i in md.disasm(code[off:], base + off):
                yield i
                last = i.address + i.size - base
            off = last + 1
    for i in insns(code, lo):
        branch = i.mnemonic.startswith('j') or i.mnemonic in ('call', 'loop')
        for op in i.operands:
            if op.type == X86_OP_MEM and i.disp_size == 4 and (TEXT[0] <= (op.mem.disp & 0xFFFFFFFF) < DATA[1]):
                v = op.mem.disp & 0xFFFFFFFF
                print("    {0x%X, %d}," % (i.address + i.disp_offset - SPAN[0], 1 if v < TEXT[1] else 0))
            elif op.type == X86_OP_IMM and not branch and i.imm_size == 4 and TEXT[0] <= (op.imm & 0xFFFFFFFF) < DATA[1]:
                v = op.imm & 0xFFFFFFFF
                print("    {0x%X, %d}," % (i.address + i.imm_offset - SPAN[0], 1 if v < TEXT[1] else 0))
print("};")
