// P2B-04b follow-up unit test: the shim's RpGeometryUnlock tristrip path (geometry.cpp + geometry_strip.cpp = the exe's mesh sort 0x8247E0/0x759640 +
// tristrip generator 0x7591D0, default method) against index streams dumped from the EXE itself running under Unicorn
// (tools/standalone/gen_strip_cases.py -> rw_strip_cases.inc). Byte-for-byte: mesh order, per-mesh index count and every index.
// Runs under Wine (device-less engine, no game data). Exit code 0 = all checks passed.
#include "fakerw.h"

#include <array>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <vector>

static int g_fail = 0, g_pass = 0;
#define CHECK(c) do { if (c) { ++g_pass; } else { ++g_fail; std::printf("  FAIL %s:%d  %s\n", __FILE__, __LINE__, #c); } } while (0)

// kind 0: explicit triangles (v0, v1, v2, material) and expected meshes (material, count, indices...); kind 1/2: generated by the same formulas as the
// Python generator, only the total index count and the FNV-1a hash over all meshes (material, count, indices as uint16) are embedded.
struct StripCase {
    const char* name; int kind; int nVerts; int nMats; const uint8_t* alpha;
    int nTris; const uint16_t* tris; int nMeshes; const uint16_t* exp; int total; uint32_t hash;
};
#include "rw_strip_cases.inc"

using Tri4 = std::array<uint16_t, 4>;
static uint32_t Lcg(uint32_t s) { return (s * 1103515245u + 12345u) & 0x7fffffffu; }
static void Shuffle(std::vector<Tri4>& l, uint32_t seed) {
    uint32_t s = seed;
    for (int i = (int)l.size() - 1; i > 0; i--) { s = Lcg(s); const int j = (int)(s % (uint32_t)(i + 1)); std::swap(l[i], l[j]); }
}
static std::vector<Tri4> Grid(int w, int h, int nm) {
    std::vector<Tri4> t;
    for (int y = 0; y < h; y++) for (int x = 0; x < w; x++) {
        const int a = y * (w + 1) + x, b = a + 1, c = a + (w + 1), e = c + 1, m = (x / 4 + y / 3) % nm;
        t.push_back({(uint16_t)a, (uint16_t)c, (uint16_t)b, (uint16_t)m});
        t.push_back({(uint16_t)b, (uint16_t)c, (uint16_t)e, (uint16_t)m});
    }
    return t;
}
static std::vector<Tri4> Soup(int n, int nv, uint32_t seed, int nm) {
    std::vector<Tri4> t; uint32_t s = seed;
    while ((int)t.size() < n) {
        s = Lcg(s); const uint32_t a = s % nv; s = Lcg(s); const uint32_t b = s % nv; s = Lcg(s); const uint32_t c = s % nv;
        if (a != b && b != c && a != c) t.push_back({(uint16_t)a, (uint16_t)b, (uint16_t)c, (uint16_t)(t.size() % nm)});
    }
    return t;
}
struct Fnv {
    uint32_t h = 0x811c9dc5u;
    void U16(uint16_t v) { for (int i = 0; i < 2; i++) { h = (h ^ ((v >> (8 * i)) & 0xFF)) * 0x01000193u; } }
};

static void RunCase(const StripCase& c) {
    std::printf("[%s]\n", c.name);
    std::vector<Tri4> tris;
    if (c.kind == 0) {
        for (int i = 0; i < c.nTris; i++) tris.push_back({c.tris[4 * i], c.tris[4 * i + 1], c.tris[4 * i + 2], c.tris[4 * i + 3]});
    } else if (c.kind == 1) {
        tris = Grid(30, 20, 3); Shuffle(tris, 5);
    } else {
        tris = Soup(800, 200, 11, 1);
    }
    CHECK((int)tris.size() == c.nTris);
    RpGeometry* g = RpGeometryCreate(c.nVerts, c.nTris, rpGEOMETRYTRISTRIP | rpGEOMETRYTEXTURED);
    std::vector<RpMaterial*> mats;
    for (int m = 0; m < c.nMats; m++) { mats.push_back(RpMaterialCreate()); mats.back()->color.alpha = c.alpha[m]; }
    RpGeometryLock(g, rpGEOMETRYLOCKALL);
    RpTriangle* t = RpGeometryGetTriangles(g);
    for (int m = 0; m < c.nMats; m++) RpGeometryTriangleSetMaterial(g, &t[0], mats[m]);  // material list order = index order
    for (int i = 0; i < c.nTris; i++) {
        RpGeometryTriangleSetVertexIndices(g, &t[i], tris[i][0], tris[i][1], tris[i][2]);
        RpGeometryTriangleSetMaterial(g, &t[i], mats[tris[i][3]]);
    }
    CHECK(RpGeometryUnlock(g) == g && g->meshHeader && g->meshHeader->flags == 1);
    if (!g->meshHeader) return;
    RpMeshHeader* h = g->meshHeader;
    CHECK((int)h->numMeshes == c.nMeshes);
    RpMesh* mesh = h->getMeshes();
    uint32_t total = 0; Fnv f; int bad = 0;
    const uint16_t* e = c.exp;
    for (unsigned i = 0; i < h->numMeshes; i++, mesh++) {
        int mi = -1;
        for (int m = 0; m < c.nMats; m++) if (mesh->material == mats[m]) mi = m;
        f.U16((uint16_t)mi); f.U16((uint16_t)mesh->numIndices);
        for (unsigned k = 0; k < mesh->numIndices; k++) f.U16(mesh->indices[k]);
        total += mesh->numIndices;
        if (c.kind == 0) {
            if (mi != e[0] || (int)mesh->numIndices != e[1]) { bad++; std::printf("  mesh %u: material %d count %u, exe: material %d count %d\n", i, mi, mesh->numIndices, e[0], e[1]); }
            else for (unsigned k = 0; k < mesh->numIndices; k++) if (mesh->indices[k] != e[2 + k]) { bad++; std::printf("  mesh %u index %u: %u, exe: %u\n", i, k, mesh->indices[k], e[2 + k]); break; }
            e += 2 + e[1];
        }
    }
    CHECK(bad == 0);
    CHECK((int)total == c.total);
    CHECK(f.h == c.hash);
    std::printf("  %d triangles -> %u indices in %u meshes, hash %08x %s\n", c.nTris, total, h->numMeshes, f.h, f.h == c.hash ? "== exe" : "!= exe");
    RpGeometryDestroy(g);
    for (RpMaterial* m : mats) RpMaterialDestroy(m);
}

int main() {
    std::setvbuf(stdout, nullptr, _IONBF, 0);
    _set_error_mode(_OUT_TO_STDERR);
    _set_abort_behavior(0, _WRITE_ABORT_MSG | _CALL_REPORTFAULT);
    HWND wnd = CreateWindowA("STATIC", "rw_strip_test", WS_OVERLAPPEDWINDOW, 0, 0, 320, 240, nullptr, nullptr, GetModuleHandleA(nullptr), nullptr);
    CHECK(wnd != nullptr);
    rw::MemoryFunctions mf{};
    mf.rwmalloc  = [](size_t sz, unsigned) -> void* { return sz ? std::malloc(sz) : nullptr; };
    mf.rwrealloc = [](void* p, size_t sz, unsigned) -> void* { return std::realloc(p, sz); };
    mf.rwfree    = [](void* p) { std::free(p); };
    CHECK(rw::Engine::init(&mf));
    CHECK(RpWorldPluginAttach() == TRUE);
    rw::EngineOpenParams params{};
    params.window = wnd;
    rw::d3d::renderdevice.system = [](rw::DeviceReq, void*, int32_t) -> int32_t { return 1; };
    CHECK(rw::Engine::open(&params));
    rw::Engine::s_plglist.construct(rw::engine);

    for (const StripCase& c : kCases) RunCase(c);

    rw::Engine::s_plglist.destruct(rw::engine);
    DestroyWindow(wnd);
    std::printf("\nrw_strip_test: %d checks passed, %d failed\n%s\n", g_pass, g_fail, g_fail ? "FAILED" : "PASSED");
    return g_fail;
}
